repos:
  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: npm run lint
        language: system
        pass_filenames: true
      - id: format
        name: format
        entry: npm run format
        language: system
        pass_filenames: true
