# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

input_datetime:
  development:
    name: Development
    has_date: true
    has_time: true

lovelace:
  mode: yaml
  resources:
    - url: /local/datetime-card/datetime-card.js
      type: module