services:
  homeassistant:
    platform: linux/amd64
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    ports:
      - 8123:8123
    volumes:
      - ./dist:/config/www/datetime-card/:ro
      - ./configuration.yaml:/config/configuration.yaml:ro
